export const QUERY_GLOBAL_NAME = 'QUERY_GLOBAL_NAME';

export const UPDATE_GLOBAL_NAME = 'UPDATE_GLOBAL_NAME';

export const UPDATE_GLOBAL_AGE = 'UPDATE_GLOBAL_AGE';

export const UPDATE_GLOBAL_NICKNAME = 'UPDATE_GLOBAL_NICKNAME';